apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:a98bb780b45f35b60c833663a2681a6eecb95990
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
